# Generated by Django 3.1.5 on 2021-01-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='privacy',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], db_index=True, default='PUBLIC', help_text='Whether the direct descendants (not files inside subfolders) inside the folder can ', max_length=10),
        ),
    ]
