# Generated by Django 3.2 on 2021-04-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210411_1527'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folder',
            name='core_folder_unique_name_parent_nullable',
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(parent__isnull=True), fields=('name', 'space_id'), name='core_folder_unique_name_parent_nullable'),
        ),
    ]
