# Generated by Django 3.1.5 on 2021-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
